# Generated by Django 3.2.7 on 2021-09-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210910_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='service_user',
            field=models.BooleanField(default=False),
        ),
    ]
